#!/usr/bin/env bash
# run-lifecycle.sh — Re-run HyperPod lifecycle scripts on existing cluster nodes
# via SSM, without replacing the nodes or redeploying the stack.
#
# When to use:
#   - You changed a lifecycle script (e.g. register_slurm_features.sh) and want
#     to apply it to existing nodes
#   - You pulled an upstream update and want to refresh all lifecycle scripts
#     across the cluster
#
# Why SSM: works even when Slurm, SSH, or /fsx is broken. The only prerequisite
# is that the SSM agent is running on the node (always true on HyperPod AMIs).
#
# Usage:
#   run-lifecycle.sh --node <hostname> [--script <name> [args...]]
#   run-lifecycle.sh --group <group-name> [--script <name> [args...]]
#   run-lifecycle.sh --all [--script <name> [args...]]
#
#   Without --script, runs the full lifecycle_script.py orchestrator (same as
#   on_create.sh does at node creation time).
#
# Options:
#   --node <hostname>        Single node by Slurm hostname (e.g. ip-10-0-2-124)
#   --group <name>           All nodes in an instance group (controller-machine,
#                            login-group, gpu-workers, cpu-workers, etc.)
#   --all                    All nodes in the cluster
#   --script <name> [args]   Run a specific script instead of the full orchestrator
#   --cluster <name>         Override PhysaiClusterStack auto-detection
#   --dry-run                Print the plan; don't execute
#   --profile, --region      Pass-through to aws
#   -h, --help
set -euo pipefail

# ---------- Arg parsing ----------
TARGET_NODE=""
TARGET_GROUP=""
TARGET_ALL=false
SCRIPT_NAME=""
SCRIPT_ARGS=()
CLUSTER=""
DRY_RUN=false
AWS_ARGS=()

usage() {
    # Print the leading comment block (everything between the shebang and the
    # first non-comment line), with the `# ` prefix stripped.
    awk '
        NR == 1 && /^#!/ { next }      # skip shebang
        /^#/ { sub(/^# ?/, ""); print; next }
        { exit }                       # stop at first non-comment line
    ' "$0"
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        --node)    TARGET_NODE="$2"; shift 2 ;;
        --group)   TARGET_GROUP="$2"; shift 2 ;;
        --all)     TARGET_ALL=true; shift ;;
        --script)  SCRIPT_NAME="$2"; shift 2
                   # Collect remaining positional args as script args, until
                   # we hit another flag
                   while [[ $# -gt 0 && "$1" != --* ]]; do
                       SCRIPT_ARGS+=("$1")
                       shift
                   done
                   ;;
        --cluster) CLUSTER="$2"; shift 2 ;;
        --dry-run) DRY_RUN=true; shift ;;
        --profile) AWS_ARGS+=(--profile "$2"); shift 2 ;;
        --region)  AWS_ARGS+=(--region "$2"); shift 2 ;;
        -h|--help) usage; exit 0 ;;
        *) echo "Unknown arg: $1" >&2; usage >&2; exit 2 ;;
    esac
done

# Exactly one target must be specified
n_targets=0
[[ -n "$TARGET_NODE"  ]] && n_targets=$((n_targets+1))
[[ -n "$TARGET_GROUP" ]] && n_targets=$((n_targets+1))
$TARGET_ALL             && n_targets=$((n_targets+1))
if [[ $n_targets -ne 1 ]]; then
    echo "ERROR: specify exactly one of --node, --group, --all" >&2
    usage >&2
    exit 2
fi

# ---------- Cluster discovery ----------
if [[ -z "$CLUSTER" ]]; then
    # shellcheck disable=SC2016  # backticks here are JMESPath, not shell
    CLUSTER=$(aws ${AWS_ARGS[@]+"${AWS_ARGS[@]}"} cloudformation describe-stacks \
        --stack-name PhysaiClusterStack \
        --query 'Stacks[0].Outputs[?OutputKey==`ClusterName`].OutputValue' \
        --output text 2>/dev/null || echo "")
    if [[ -z "$CLUSTER" || "$CLUSTER" == "None" ]]; then
        echo "ERROR: could not auto-detect cluster name. Pass --cluster <name>." >&2
        exit 1
    fi
fi
echo "Cluster: $CLUSTER"

# Derive cluster ID for SSM target construction
CLUSTER_ID=$(aws ${AWS_ARGS[@]+"${AWS_ARGS[@]}"} sagemaker describe-cluster \
    --cluster-name "$CLUSTER" --query 'ClusterArn' --output text \
    | awk -F/ '{print $NF}')

# Resolve the cluster's lifecycle S3 prefix so we can pull non-script artifacts
# (specifically physai-config.json — generated by CDK at deploy time and not
# present in infra/lifecycle/ on disk). Without this, configure_slurm_accounting.sh
# self-skips with "No physai-config.json found".
LIFECYCLE_S3_URI=$(aws ${AWS_ARGS[@]+"${AWS_ARGS[@]}"} sagemaker describe-cluster \
    --cluster-name "$CLUSTER" \
    --query 'InstanceGroups[0].LifeCycleConfig.SourceS3Uri' --output text 2>/dev/null || echo "")
if [[ -z "$LIFECYCLE_S3_URI" || "$LIFECYCLE_S3_URI" == "None" ]]; then
    echo "ERROR: could not resolve lifecycle SourceS3Uri from cluster" >&2
    exit 1
fi
LIFECYCLE_S3_URI="${LIFECYCLE_S3_URI%/}"  # strip trailing slash

# List all cluster nodes: (Group, InstanceId, Hostname).
# PrivateDnsHostname is like "ip-10-0-2-124.us-west-2.compute.internal";
# the Slurm NodeName is the short form "ip-10-0-2-124".
NODES_JSON=$(aws ${AWS_ARGS[@]+"${AWS_ARGS[@]}"} sagemaker list-cluster-nodes \
    --cluster-name "$CLUSTER" \
    --query 'ClusterNodeSummaries[].{Group:InstanceGroupName,InstanceId:InstanceId,Dns:PrivateDnsHostname}' \
    --output json)

# Build list of (Group, InstanceId, Hostname) tuples as tab-separated lines
ALL_NODES=$(python3 <<PY
import json
nodes = json.loads("""$NODES_JSON""")
if not nodes:
    raise SystemExit("no nodes returned")
for n in nodes:
    dns = n.get("Dns") or ""
    host = dns.split(".")[0] if dns else ""
    print(f"{n['Group']}\t{n['InstanceId']}\t{host}")
PY
)

# ---------- Filter to target nodes ----------
SELECTED_NODES=""
if [[ -n "$TARGET_NODE" ]]; then
    SELECTED_NODES=$(echo "$ALL_NODES" | awk -F'\t' -v h="$TARGET_NODE" '$3 == h')
    if [[ -z "$SELECTED_NODES" ]]; then
        echo "ERROR: node '$TARGET_NODE' not found in cluster. Available hostnames:" >&2
        echo "$ALL_NODES" | awk -F'\t' '{print "  " $3 "  (" $1 ")"}' >&2
        exit 1
    fi
elif [[ -n "$TARGET_GROUP" ]]; then
    SELECTED_NODES=$(echo "$ALL_NODES" | awk -F'\t' -v g="$TARGET_GROUP" '$1 == g')
    if [[ -z "$SELECTED_NODES" ]]; then
        echo "ERROR: group '$TARGET_GROUP' has no nodes. Available groups:" >&2
        echo "$ALL_NODES" | awk -F'\t' '{print $1}' | sort -u | sed 's/^/  /' >&2
        exit 1
    fi
else
    SELECTED_NODES="$ALL_NODES"
fi

# ---------- Package lifecycle/ ----------
REPO_ROOT=$(cd "$(dirname "$0")/../.." && pwd)
LIFECYCLE_DIR="$REPO_ROOT/infra/lifecycle"
if [[ ! -d "$LIFECYCLE_DIR" ]]; then
    echo "ERROR: lifecycle directory not found at $LIFECYCLE_DIR" >&2
    exit 1
fi

echo "Packaging $LIFECYCLE_DIR..."
# base64 -w0 on Linux / -b0 on macOS — use python for portability.
# COPYFILE_DISABLE=1 prevents macOS from adding ._* AppleDouble metadata files.
# (Other macOS extended attributes may still appear in the tar, producing
# harmless 'Ignoring unknown extended header' warnings on the remote gnu
# tar — we discard those in the remote extract step.)
TAR_B64=$(COPYFILE_DISABLE=1 tar czf - \
    --exclude='__pycache__' --exclude='.mypy_cache' --exclude='._*' \
    -C "$LIFECYCLE_DIR" . \
    | python3 -c 'import sys,base64; sys.stdout.write(base64.b64encode(sys.stdin.buffer.read()).decode())')
TAR_B64_SIZE=$(echo -n "$TAR_B64" | wc -c | tr -d ' ')

# AWS StartSession caps each --parameters value at 65,535 chars
# (https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_StartSession.html).
# We pass the command as `bash -c "echo <REMOTE_B64> | base64 -d | bash"`
# where REMOTE_B64 is base64 of the remote bash script, which itself
# inlines TAR_B64 literally. So the outgoing parameter is roughly:
#
#   len(command_param) ≈ 30 (wrapper: `bash -c "echo ... | base64 -d | bash"`)
#                      + ceil(len(REMOTE_SCRIPT) × 4/3)    (outer base64)
#
# and len(REMOTE_SCRIPT) ≈ 160 (wrapper boilerplate) + TAR_B64_SIZE.
#
# Inverting: given a limit L on the outgoing parameter, the max TAR_B64
# size is roughly ((L - 30) × 3/4) - 160. With L = 65,535 that's ~48,990.
# We subtract a generous 2,000-byte safety margin, giving ~47,000 bytes
# of base64 tar ≈ 35 KB raw.
SSM_PARAM_LIMIT=65535
WRAPPER_OVERHEAD=2000
SSM_PAYLOAD_BUDGET=$(( (SSM_PARAM_LIMIT * 3 / 4) - WRAPPER_OVERHEAD ))
echo "  payload size: $TAR_B64_SIZE bytes (budget: $SSM_PAYLOAD_BUDGET bytes)"
if [[ $TAR_B64_SIZE -gt $SSM_PAYLOAD_BUDGET ]]; then
    cat >&2 <<EOF
ERROR: lifecycle payload too large for SSM start-session.

  base64 tarball:     $TAR_B64_SIZE bytes
  budget:             $SSM_PAYLOAD_BUDGET bytes

The tarball is embedded in the SSM start-session 'command' parameter,
which is capped at $SSM_PARAM_LIMIT chars by the AWS API. After the second
base64 encoding and wrapper overhead, a tarball larger than the budget
above would exceed that cap. You're over — run-lifecycle.sh needs to
switch to a different transport.

Options:
  1. Upload the tarball to S3 (e.g. the existing lifecycle-scripts bucket)
     and have the remote bootstrap curl it down before extracting.
  2. Move large files out of infra/lifecycle/ (e.g. fetch heavy binaries at
     runtime from S3 instead of shipping them in the tarball).

Until run-lifecycle.sh is updated, you can still apply lifecycle changes by:

  (a) Redeploying the cluster stack (\`npx cdk deploy PhysaiClusterStack\`)
      and replacing worker/login nodes with \`scontrol update node=<name>
      state=fail reason="Action:Replace"\`. Doesn't cover the controller.

  (b) Destroying and redeploying PhysaiClusterStack end-to-end
      (\`npx cdk destroy PhysaiClusterStack && npx cdk deploy
      PhysaiClusterStack\`). Slow (~25 min) but covers every node including
      the controller. PhysaiClusterStack is stateless; PhysaiInfraStack
      (FSx, RDS, S3 data bucket) is untouched.

Both paths use the S3 bucket, which has no such size cap. See
docs/USER_MANUAL.md for the full workflow.
EOF
    exit 1
fi

# ---------- Plan ----------
echo
echo "Plan:"
if [[ -n "$SCRIPT_NAME" ]]; then
    echo "  Script:  $SCRIPT_NAME ${SCRIPT_ARGS[*]:-}"
else
    echo "  Script:  (full lifecycle_script.py orchestrator)"
fi
echo "  Targets:"
while IFS=$'\t' read -r group iid host; do
    echo "    $host  ($group, $iid)"
done <<< "$SELECTED_NODES"

if $DRY_RUN; then
    echo
    echo "--dry-run: not executing."
    exit 0
fi

# ---------- Set up logging ----------
RUN_ID=$(date -u +%Y%m%dT%H%M%SZ)
LOG_DIR="/tmp/physai-lifecycle-runs/$RUN_ID"
mkdir -p "$LOG_DIR"
echo
echo "Logs: $LOG_DIR"
echo

# ---------- Remote script template ----------
# This is what runs on each target node. It:
#   1. Extracts the base64 tar into a staging dir
#   2. Sets env vars the same way on_create.sh does
#   3. Runs either lifecycle_script.py or a specific script
#
# The TAR_B64 placeholder is substituted per-node (though content is the same).
build_remote_script() {
    local script_name="$1"; shift
    local script_args=("$@")
    local args_str=""
    if [[ ${#script_args[@]} -gt 0 ]]; then
        # Quote each arg for bash
        printf -v args_str ' %q' "${script_args[@]}"
    fi

    cat <<REMOTE_EOF
set -e
STAGE=/tmp/physai-lifecycle-staging
rm -rf "\$STAGE"
mkdir -p "\$STAGE"
echo '$TAR_B64' | base64 -d | tar xzf - -C "\$STAGE" 2>/dev/null
cd "\$STAGE"
# Pull physai-config.json from the cluster's lifecycle S3 prefix. This file is
# generated at \`cdk deploy\` time and shipped alongside the scripts in S3, so
# it isn't in the local infra/lifecycle/ tarball. configure_slurm_accounting.sh
# requires it; without this fetch it self-skips on "No physai-config.json".
# Best-effort: the AWS CLI is available on HyperPod nodes; if the fetch fails
# we let the script self-skip with its existing message rather than fail here.
aws s3 cp "$LIFECYCLE_S3_URI/physai-config.json" "\$STAGE/physai-config.json" --quiet 2>/dev/null || true
export SAGEMAKER_RESOURCE_CONFIG_PATH=/opt/ml/config/resource_config.json
# Discover SLURM_DIR the same way lifecycle_script.py does: prefer /opt/slurm
# (typically a symlink to the active install) to avoid picking up a staged
# but inactive version like /opt/slurm-25.11 that would cause RPC version
# mismatches with slurmctld.
if [ -e /opt/slurm ]; then
    SLURM_DIR="\$(readlink -f /opt/slurm)"
else
    for conf in /opt/slurm*/etc/slurm.conf; do
        if [ -f "\$conf" ]; then
            SLURM_DIR="\$(dirname "\$(dirname "\$conf")")"
            break
        fi
    done
fi
export SLURM_DIR="\${SLURM_DIR:-/opt/slurm}"
echo "SLURM_DIR=\$SLURM_DIR"
if [ -n "$script_name" ]; then
    bash "$script_name"${args_str}
else
    python3 -u lifecycle_script.py --resource-config "\$SAGEMAKER_RESOURCE_CONFIG_PATH"
fi
REMOTE_EOF
}

REMOTE_SCRIPT=$(build_remote_script "$SCRIPT_NAME" "${SCRIPT_ARGS[@]+"${SCRIPT_ARGS[@]}"}")

# ---------- Execute on each node ----------
# Build JSON parameters for SSM: the command is a single "bash -c '<script>'"
# We base64-encode the whole remote script to avoid shell escaping nightmares.
REMOTE_B64=$(printf '%s' "$REMOTE_SCRIPT" | python3 -c 'import sys,base64; sys.stdout.write(base64.b64encode(sys.stdin.buffer.read()).decode())')

OVERALL_RESULT=0
declare -a RESULTS=()

run_on_node() {
    local group="$1"
    local iid="$2"
    local host="$3"
    local ssm_target="sagemaker-cluster:${CLUSTER_ID}_${group}-${iid}"
    local log_file="$LOG_DIR/${host:-$iid}.log"
    local start_ts end_ts duration

    start_ts=$(date -u +%s)
    echo "[$(date -u +%H:%M:%S)] $host ($group): dispatching via SSM..."

    # The remote command decodes our base64 blob and execs it. Build params
    # JSON with separateOutputStream=true so the agent appends 'EXIT_CODE: N'
    # to the stream -- that's how we know whether the remote command succeeded.
    local params_json
    params_json=$(python3 <<PY
import json, sys
cmd = 'bash -c "echo $REMOTE_B64 | base64 -d | bash"'
print(json.dumps({
    "command": [cmd],
    "separateOutputStream": ["true"],
}))
PY
)

    # Wrap aws ssm start-session with \`script\` to allocate a PTY. Without a
    # PTY, session-manager-plugin closes the data channel before all output
    # has been delivered (verified empirically against AWS-StartNonInteractiveCommand
    # when the remote command invokes systemctl).
    #
    # \`script\` flags differ: Linux (util-linux) uses \`-c CMD\`, BSD/macOS
    # uses positional args.
    local script_rc=0
    if script --version 2>&1 | grep -qi util-linux; then
        script -q -c "aws ${AWS_ARGS[*]:-} ssm start-session --target '$ssm_target' --document-name AWS-StartNonInteractiveCommand --parameters '$params_json'" /dev/null \
            > "$log_file.raw" 2>&1 || script_rc=$?
    else
        script -q /dev/null aws ${AWS_ARGS[@]+"${AWS_ARGS[@]}"} ssm start-session \
            --target "$ssm_target" \
            --document-name AWS-StartNonInteractiveCommand \
            --parameters "$params_json" \
            > "$log_file.raw" 2>&1 || script_rc=$?
    fi

    # Strip CR characters inserted by the PTY
    tr -d '\r' < "$log_file.raw" > "$log_file"
    rm -f "$log_file.raw"

    end_ts=$(date -u +%s)
    duration=$((end_ts - start_ts))

    # Parse remote exit code. separateOutputStream=true appends 'EXIT_CODE: N'.
    # If not present, treat as failure (session died before command completed).
    local remote_rc
    remote_rc=$(grep -oE '^EXIT_CODE: [0-9]+' "$log_file" | tail -1 | awk '{print $2}')
    if [[ -z "$remote_rc" ]]; then
        echo "[$(date -u +%H:%M:%S)] $host: FAILED (no EXIT_CODE in output; session-rc=$script_rc, ${duration}s) -- see $log_file"
        RESULTS+=("$host	FAILED	no-exit-code ${duration}s")
        OVERALL_RESULT=1
    elif [[ "$remote_rc" == "0" ]]; then
        echo "[$(date -u +%H:%M:%S)] $host: SUCCESS (${duration}s)"
        RESULTS+=("$host	SUCCESS	${duration}s")
    else
        echo "[$(date -u +%H:%M:%S)] $host: FAILED (remote exit=$remote_rc, ${duration}s) -- see $log_file"
        RESULTS+=("$host	FAILED	exit=$remote_rc ${duration}s")
        OVERALL_RESULT=1
    fi
}

while IFS=$'\t' read -r group iid host <&3; do
    run_on_node "$group" "$iid" "$host"
done 3<<< "$SELECTED_NODES"

# ---------- Summary ----------
echo
echo "=== Summary ==="
printf '%s\n' "${RESULTS[@]}" | awk -F'\t' '{printf "  %-20s %-10s %s\n", $1, $2, $3}'
echo
echo "Full logs: $LOG_DIR"

exit $OVERALL_RESULT
